apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-pytest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: es-pytest
  template:
    metadata:
      labels:
        app: es-pytest
    spec:
      containers:
        - name: es-pytest
          image: gabriel04alves/es-pytest
          ports:
            - containerPort: 8000
